name: Publish

on:
  push:
    tags:
      - 'v*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Login to image repository
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: kapetacom/mongodb-replicaset
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: kapetacom/mongodb-replicaset

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
