name: Publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: kapetacom/mongodb-replicaset
            flavor: latest=true
            tags: |
              type=semver,pattern={{version}}
              type=sha,format=long,prefix=

        - name: Login to image repository
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

        - name: checkout action
          uses: actions/checkout@v3
          with:
            repository: kapetacom/core-deploy-action
            path: ./github-action/core-deploy-action
            token: ${{ secrets.GHA_TOKEN }}

        - name: deploy to Kapeta cloud
          uses: ./github-action/core-deploy-action
          env:
            GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
          with:
            image: kapetacom/mongodb-replicaset
            tag: ${{ github.sha }}